version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
    - 1883:1883
    volumes:
    - ./mosquitto:/mosquitto/config
  
  nodered:
    image: nodered/node-red
    ports:
    - 1880:1880
    volumes:
    - ./nodered/:/data/